create table avgWeekday SELECT weekday(d.date) as weekday, 'rainy' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation > 0 or w.snowfall > 0) and weekday(d.date) = 0 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'rainy' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation > 0 or w.snowfall > 0) and weekday(d.date) = 1 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'rainy' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation > 0 or w.snowfall > 0) and weekday(d.date) = 2 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'rainy' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation > 0 or w.snowfall > 0) and weekday(d.date) = 3 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'rainy' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation > 0 or w.snowfall > 0) and weekday(d.date) = 4 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'rainy' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation > 0 or w.snowfall > 0) and weekday(d.date) = 5 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'rainy' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation > 0 or w.snowfall > 0) and weekday(d.date) = 6 and d.date = w.date;

insert into avgWeekday SELECT weekday(d.date) as weekday, 'all' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where weekday(d.date) = 0 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'all' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where weekday(d.date) = 1 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'all' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where weekday(d.date) = 2 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'all' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where weekday(d.date) = 3 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'all' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where weekday(d.date) = 4 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'all' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where weekday(d.date) = 5 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'all' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where weekday(d.date) = 6 and d.date = w.date;

insert into avgWeekday SELECT weekday(d.date) as weekday, 'clear' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation = 0 and w.snowfall = 0) and weekday(d.date) = 0 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'clear' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation = 0 and w.snowfall = 0) and weekday(d.date) = 1 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'clear' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation = 0 and w.snowfall = 0) and weekday(d.date) = 2 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'clear' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation = 0 and w.snowfall = 0) and weekday(d.date) = 3 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'clear' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation = 0 and w.snowfall = 0) and weekday(d.date) = 4 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'clear' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation = 0 and w.snowfall = 0) and weekday(d.date) = 5 and d.date = w.date;
insert into avgWeekday SELECT weekday(d.date) as weekday, 'clear' as modus, avg(speedViolations) as avgSpeedViolations, avg(totalMotorVehicle) as avgMotorVehicle, avg(total0) as avgPedestrian, avg(total1) as avgCycle from hourly_traffic_data d, meteoblue_weather w where (w.precipitation = 0 and w.snowfall = 0) and weekday(d.date) = 6 and d.date = w.date;
